% Initialize matrix A and B 
A = [1, 2, 4; 5, 3, 2]
B = [1, 3, 4; 1, 1, 1]

% Initialize constant s 
s = 2

% See how element-wise addition works
add_AB = A + B 

% See how element-wise subtraction works
sub_AB = A - B

% See how scalar multiplication works
mult_As = A * s

% Divide A by s
div_As = A / s

% What happens if we have a Matrix + scalar?
add_As = A + s

In [2]:
import numpy as np

In [3]:
A = [[1, 2, 4], 
     [5, 3, 2]]
B = [[1, 3, 4], 
     [1, 1, 1]]
s=2

In [21]:
# initialize of marices and constant
print(np.array(A))
print(np.array(A)[0,0])

[[1 2 4]
 [5 3 2]]
1


In [13]:
# Addition of matrices
np.add(A,B)

array([[2, 5, 8],
       [6, 4, 3]])

In [14]:
#subtraction of matrices
np.subtract(A,B)

array([[ 0, -1,  0],
       [ 4,  2,  1]])

In [38]:
# Scalar Multiplication of Matrix
print(np.dot(A,s))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [19]:
# Scalar division of matrix
print(np.divide(A,s))

[[0.5 1.  2. ]
 [2.5 1.5 1. ]]


# Matrix Vector Multiplication
% Initialize matrix A 
A = [1, 2, 3; 4, 5, 6;7, 8, 9] 

% Initialize vector v 
v = [1; 1; 1] 

% Multiply A * v
Av = A * v

In [27]:
# Initialization
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
V = np.array([[1],[1],[1]])

In [39]:
# Matrix multiplication
#np.matmul(A,V)
np.dot(A,V)

array([[ 6],
       [15],
       [24]])

In [40]:
house = np.array([[1, 2104],[1,1416],[1,1534],[1,852]])
hypo= np.array([[-40, 200, -150],[0.25, 0.1, 0.4]])

In [43]:
#Matrix Matrix multiplication
print(np.matmul(house, hypo))
print(np.dot(house,hypo))

[[486.  410.4 691.6]
 [314.  341.6 416.4]
 [343.5 353.4 463.6]
 [173.  285.2 190.8]]
[[486.  410.4 691.6]
 [314.  341.6 416.4]
 [343.5 353.4 463.6]
 [173.  285.2 190.8]]


% Initialize a 3 by 2 matrix 
A = [1, 2; 3, 4;5, 6]

% Initialize a 2 by 1 matrix 
B = [1; 2] 

% We expect a resulting matrix of (3 by 2)*(2 by 1) = (3 by 1) 
mult_AB = A*B

% Make sure you understand why we got that result

In [50]:
A = [[1,2],[3,4],[5,6]]
B = [[1],[2]]

In [52]:
np.matmul(A,B)

array([[ 5],
       [11],
       [17]])

% Initialize random matrices A and B 
A = [1,2;4,5]
B = [1,1;0,2]

% Initialize a 2 by 2 identity matrix
I = eye(2)

% The above notation is the same as I = [1,0;0,1]

% What happens when we multiply I*A ? 
IA = I*A 

% How about A*I ? 
AI = A*I 

% Compute A*B 
AB = A*B 

% Is it equal to B*A? 
BA = B*A 

% Note that IA = AI but AB != BA

In [56]:
# identity matrix
A = [[1,2],[4,5]]
B = [[1,1],[0,2]]
i2 = np.identity(2)

In [57]:
# A*I=I*A=A
print(np.dot(A,i2))
print(np.dot(i2,A))

[[1. 2.]
 [4. 5.]]
[[1. 2.]
 [4. 5.]]


In [58]:
# A*B!=B*A
print(np.dot(A,B))
print(np.dot(B,A))

[[ 1  5]
 [ 4 14]]
[[ 5  7]
 [ 8 10]]


% Initialize matrix A 
A = [1,2,0;0,5,6;7,0,9]

% Transpose A 
A_trans = A' 

% Take the inverse of A 
A_inv = inv(A)

% What is A^(-1)*A? 
A_invA = inv(A)*A

In [80]:
A = np.array([[1,2,0],[0,5,6],[7,0,9]])
A

array([[1, 2, 0],
       [0, 5, 6],
       [7, 0, 9]])

In [81]:
invA = np.linalg.inv(A)
invA

array([[ 0.34883721, -0.13953488,  0.09302326],
       [ 0.3255814 ,  0.06976744, -0.04651163],
       [-0.27131783,  0.10852713,  0.03875969]])

In [82]:
tpA= np.transpose(A)
tpA

array([[1, 0, 7],
       [2, 5, 0],
       [0, 6, 9]])

In [83]:
invA.dot(A)

array([[ 1.00000000e+00,  0.00000000e+00,  1.80411242e-16],
       [ 2.08166817e-17,  1.00000000e+00,  3.46944695e-17],
       [-3.46944695e-17,  0.00000000e+00,  1.00000000e+00]])